### ISSUE TITLE
It didn't connect the server.I need help!

### ISSUE THREAD

**Issue by panyunyi** [Cloud-Automation/node-modbus#111]
Hello,sorry to bother you!
I really need some help.
![image](https://cloud.githubusercontent.com/assets/8056745/21894810/7babd1f2-d91b-11e6-954c-f8055cb19d3b.png)

modscan32 is worked in this config.But jsmodbus didn't work.

**Comment by panyunyi** [comment]
![image](https://cloud.githubusercontent.com/assets/8056745/21895066/59e048d6-d91c-11e6-9ce7-4a36163aa1f3.png)

**Comment by BauchBeinePoe** [comment]
Are you sure you connect to the right port and ip address? The timeout can be from the tcp connection since you have set auto reconnect to true.

**Comment by panyunyi** [comment]
Yes,I'm sure connect to the right port and ip address.The second picture is modscan.They have same config.
![image](https://cloud.githubusercontent.com/assets/8056745/22005525/eff7a46a-dc9e-11e6-864d-f0d128b8ca41.png)
![image](https://cloud.githubusercontent.com/assets/8056745/22005551/3206c700-dc9f-11e6-835f-cac980032181.png)

**Comment by BauchBeinePoe** [comment]
Can you post the code here, so that I can reproduce.

**Comment by panyunyi** [comment]
var modbus = require('jsmodbus');

// create a modbus client
var client = modbus.client.tcp.complete({ 
        'host'              : '192.168.1.8', 
        'port'              : 10000,
        'autoReconnect'     : false,
        'reconnectTimeout'  : 1000,
        'timeout'           : 5000,
        'unitId'            : 1
    });

client.connect();

// reconnect with client.reconnect()

client.on('connect', function () {


    client.readInputRegisters(2, 10).then(function (resp) {

        // resp will look like { fc: 4, byteCount: 20, register: [ values 0 - 10 ], payload: <Buffer> }
        console.log(resp);

    }, console.error);


});

client.on('error', function (err) {

    console.log(err);

})

**Comment by BauchBeinePoe** [comment]
The best way to solve these kind of problems is to do it step by step. Try the code below. There are no modbus requests, just the connection. I would bet that this fails. If so, check your server and firewall settings.

````
var modbus = require('jsmodbus');

// create a modbus client
var client = modbus.client.tcp.complete({
    'host' : '192.168.1.8',
    'port' : 10000,
    'autoReconnect' : false,
    'reconnectTimeout' : 1000,
    'timeout' : 5000,
    'unitId' : 1
});

client.connect();

client.on('connect', function () {
    console.log("Connected!");
});

client.on('error', function (err) {
    console.log("Connection error!", err);
})
````

**Comment by panyunyi** [comment]
OK!Thank you for your patience.I will try.

**Comment by panyunyi** [comment]
Hi...It's connected.But the readInputRegisters didn't work.I think it maybe the response code is wrong.
![image](https://cloud.githubusercontent.com/assets/8056745/22064810/2c649da0-ddc0-11e6-905c-c68d64ab1660.png)
![image](https://cloud.githubusercontent.com/assets/8056745/22065387/050fbe8a-ddc3-11e6-975d-40e81ba5dc29.png)
The right code is:
0000 0000 0006 0104 0001  0014
How should I modify the demo code to success?

**Comment by panyunyi** [comment]
![image](https://cloud.githubusercontent.com/assets/8056745/22065567/cd6a9fb2-ddc3-11e6-9396-f60eb6628432.png)
It's worked!Thank you!
