### ISSUE TITLE
Feature request: make rtu / serial support optional

### ISSUE THREAD

**Issue by flottokarotto** [Cloud-Automation/node-modbus#117]
serialport is the only native dependency.
jsmodbus would be a js-only modbus solution without it.

**Comment by BauchBeinePoe** [comment]
There is an option for npm packages to declare certain dependencies as optional. This way the module will be installed even thou this optional module is missing or it's installation routine failed. So this could be done. Why do you want it to be js-only?

**Comment by flottokarotto** [comment]
For cross-build environments (e.g. open embedded), it is necessary to delete all native dependencies inside node_modules (or complete node_modules). A js-only solution would be a lot easier to deploy.

**Comment by BauchBeinePoe** [comment]
You can always fork this project without the native dependencies. Since serial is already introduced here I won't take it back, sorry.

**Comment by GermanBluefox** [comment]
I must say, that would to prefer to move serialport to optional
dependencies.
It is really optional an as far as I know almost no one use this node as
serial rtu. I want to prepare pull request to fix chanking with serial.

If you move serialport to optional you loose nothing.  The people who wants
to use this packet with serial port, they will care about properly
installation. And the people who wants to use just over tcp they are just
happy. My platform runs on very different devices, nas, arm5, and so on.
The world is not only raspi, Mac and PC.

Am 16.02.2017 15:52 schrieb "Stefan Poeter" <notifications@github.com>:

**Comment by stefanpoeter** [comment]
See branch v3.0.0-alpha:
The serialport is no longer a dependency. Yet you are able to create a rtu (serial) client.
