### ISSUE TITLE
Connect timeout feature request

### ISSUE THREAD

**Issue by klmurphy72** [Cloud-Automation/node-modbus#131]
It would be nice if there was an option for a connect timeout.  It would make connecting to a device that was just plugged in much faster!

thank you

**Comment by stefanpoeter** [comment]
What about tcp probe? There was a issue a while back.

**Comment by klmurphy72** [comment]
tcp probe?  I don't understand.  If this should mean something to me, sorry....it does not.

**Comment by stefanpoeter** [comment]
Have a look at issue #36 You can use the npm package tcp-ping to probe a tcp port. This way you can check if a modbus device is online periodically without risking a connection error.

**Comment by stefanpoeter** [comment]
Have a look at how the reconnect is handled in the v3.0.0-alpha branch. The socket logic is separated from the modbus client.
