### ISSUE TITLE
ReadDiscrete use getInput 

### ISSUE THREAD

**Issue by davidonet** [Cloud-Automation/node-modbus#145]
Why does ReadDiscrete use Input Buffer it's a bit confusing ?

https://github.com/Cloud-Automation/node-modbus/blob/321f71f15ad7f6516665bd7cc755a71232fba1b8/src/handler/server/ReadDiscreteInputs.js#L38

I can't find getDiscrete method.

**Comment by stefanpoeter** [comment]
It is indeed confusing. I'll always used it this way, there was an issue some time back that adressed this issue too. I'll try to avoid this in the v3 release.

**Comment by davidonet** [comment]
How can I avoid collision between a ReadInput(0x00) and a ReadDiscrete(0x00) ?

**Comment by stefanpoeter** [comment]
If you want to do it right then I would make a pull request and replace the input buffer with a new discrete buffer. That way you are fine.

**Comment by davidonet** [comment]
Yes please :-)

**Comment by stefanpoeter** [comment]
Sorry for the long delay. Can you confirm that this is working the way you wanted it?

**Comment by davidonet** [comment]
I've seen a pull request that seems to fix it : https://github.com/Cloud-Automation/node-modbus/pull/154
But it doesn't seem to be integrated in the current master branch : https://github.com/Cloud-Automation/node-modbus/blob/1cc5a9088a904c60470ac865c4ab2d24445cf655/src/handler/server/ReadDiscreteInputs.js#L38
There is still a getInput buffer in the ReadDiscreteInput.

**Comment by stefanpoeter** [comment]
Yes, you need to confirm that the pull request fixed the issue before I merge it into the master branch.

**Comment by davidonet** [comment]
I don't know how to test it, I tried to fork the project but I can't merge the pull request in my fork.

**Comment by davidonet** [comment]
I figure how it can be done locally : 
https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by davidonet** [comment]
Yes it works Input buffer and Discrete buffer are distinct.
tested with 
```javascript 
// in SimpleServer
this.getInput().writeUInt16BE(0xff,0)
this.getDiscrete().writeUInt8(0xaa,0)
```
and client
``` shell
$ node ReadDiscreteInput.js localhost 8888 0 1
$ node ReadInputRegister.js localhost 8888 0 1
```

**Comment by stefanpoeter** [comment]
Can you also copy the output from the  command line. Thanks.

**Comment by davidonet** [comment]
done

**Comment by stefanpoeter** [comment]
Thanks, I'll merge it soon then.
