### ISSUE TITLE
Install on Node.JS 8.+

### ISSUE THREAD

**Issue by biancode** [Cloud-Automation/node-modbus#147]
Hi,

please, could you upgrade to serialport@5.0.0 or set the preinstall in the package.json:

`"preinstall": "npm install --build-from-source serialport@4.0.7"`

serialport@4.0.7 is supported on node v8 but needs the build from source

LTS v8 comes in October

Thanks!
Klaus

**Comment by stefanpoeter** [comment]
I will do that. 

Btw. do you know if the 5.0 serialport works under ubuntu?

**Comment by biancode** [comment]
Dear Stefan,

thank you and no, I'm sorry, I didn't test with Ubuntu for now.

**Comment by stefanpoeter** [comment]
@biancode Have a look at #148. Travis CI tells mit everything is fine, can you confirm that?
