### ISSUE TITLE
Working over Modbus RTU/ASCII

### ISSUE THREAD

**Issue by bladerunner2020** [Cloud-Automation/node-modbus#15]
I have been using jsModbus module for more than year in my smart home installation. It works perfectly and I would like to thank you very much for great job.

I am working on another project where I need to access modbus devices over Modbus RTU/ASCII. I haver RS-485 to USB adaptor and I curious is it possible to use/adapt your module to use it with serial port?

**Comment by bladerunner2020** [comment]
I can test. And with some help I could try to implement this...

**Comment by bladerunner2020** [comment]
Great! Have you any idea when 0.6.0 could be released?

**Comment by BauchBeinePoe** [comment]
Have a look at the v1.0.0 alpha pull request.

**Comment by BauchBeinePoe** [comment]
Hey @bladerunner2020 can you test the v1.0.0 modbus over serial functions. Unfortunatly I can't.

**Comment by bladerunner2020** [comment]
Will try to check this week.

**Comment by bladerunner2020** [comment]
Finally I got some time for testing but got stuck with serial port. It failed to install on Win7-64. If you could help me with binaries for serial port. 

`Error: Cannot find module '/Users/Bladerunner/Documents/Node JS Projects/playwithnode/node_modules/serialport/build/Release/node-v47-darwin-x64/serialport.node'`

**Comment by BauchBeinePoe** [comment]
You better handle this on the serialports github page https://github.com/voodootikigod/node-serialport.
