### ISSUE TITLE
Add socket.unref() where needed?

### ISSUE THREAD

**Issue by cwg999** [Cloud-Automation/node-modbus#160]
Wherever you socket.close() (and don't plan to open) or socket.destroy() I think you should also use socket.unref() so that the node.js process can exit cleanly.

For example,
https://github.com/nodejs/node-convergence-archive/blob/e11fe0c2777561827cdb7207d46b0917ef3c42a7/test/parallel/test-net-socket-timeout-unref.js

I can create a pull request if you're interested, but you might have more expertise in working with sockets than I.
-Cody

**Comment by stefanpoeter** [comment]
Would be great if you can create a pull request.

**Comment by stefanpoeter** [comment]
Anything?

**Comment by cwg999** [comment]
Sorry, haven't worked on this since I saw you had a new v3
