### ISSUE TITLE
v3 Dev State

### ISSUE THREAD

**Issue by stefanpoeter** [Cloud-Automation/node-modbus#168]
The way I see it, we are missing some fcs on the TCP Server Response Handler. After that we can move to a beta phase and start testing v3. What do you think @AnthonyMujic ?

**Comment by AnthonyMujic** [comment]
I think that is a great idea. There are fc's 15 and 16 then we can test to
work out what more is required.

**Comment by AnthonyMujic** [comment]
Fc's 15 and 16 are complete.
@stefanpoeter, let me know if there are any issues, or if there is anything else in v3 you would like me to work on.

**Comment by stefanpoeter** [comment]
@AnthonyMujic great work, I would say we can move soon to a beta version and create some scripts for long running tests.

**Comment by kevingarman** [comment]
@stefanpoeter, probably not a great place to post this, but just wanted to say thanks for this project.  I've been using it a bit and it's been solid for me.  I'm testing v3 now because I need the #149 functionality...looking forward to the v3 release!

**Comment by stefanpoeter** [comment]
@kevingarman How are you tests going?

**Comment by kevingarman** [comment]
@stefanpoeter So far so good!
