### ISSUE TITLE
Upgrade to serialport 6

### ISSUE THREAD

**Issue by Apollon77** [Cloud-Automation/node-modbus#170]
hey,

I think using serialport 5.0.0 (wich was kind of an in-between version) is not that good. Upgrading to 6.0.4 should not produce any problem ... and you would have official support from serialport guys on topics.

**Comment by stefanpoeter** [comment]
hey @Apollon77 ,

thanks for the input. Did you test jsmodbus with serialport 6 and can you prepare a pull request?

**Comment by Apollon77** [comment]
I personally don't have tested it because I use serialport over TC, just noticed the "old" dependency. I decided for the issue because I can not really test it

**Comment by stefanpoeter** [comment]
You can use serialport 6 when we release jsmodbus v3.
