### ISSUE TITLE
V3 - F6 : write single register

### ISSUE THREAD

**Issue by profelec** [Cloud-Automation/node-modbus#176]
Hi,
for the example to work, I made that :
/src/tcp-server-response-handler.js
ligne 159 :
```
       } else {
   +     this._server.emit('preWriteSingleRegister', request.body.address, this._server.holding) 
         this._server.holding.writeUInt16BE(responseBody.value, responseBody.address * 2)
   +     this._server.emit('WriteSingleRegister', responseBody.address, this._server.holding) 
      	}
```

/examples/tcp/SimpleServer.js
ligne 27 :
```
     server.on('preWriteSingleRegister', function (value, address) {
	console.log('Write Single Register')
  -  	console.log('Original {register, value}: {', address, ',', server.holding.readUInt16BE(address),  '}’)
  + 	console.log('Original {register, value}: {', address, ',', server.holding.readUInt16BE(address*2), '}')
    })

     server.on('WriteSingleRegister', function (value, address) {
  -  	console.log('New {register, value}: {', address, ',', server.holding.readUInt16BE(address), '}’)
  +  	console.log('New {register, value}: {', address, ',', server.holding.readUInt16BE(address*2), '}')
     })

```

**Comment by stefanpoeter** [comment]
I am not sure these events are necessary since you can just overwrite the default request handler. What do you think?

**Comment by profelec** [comment]
I do not see how to do that.
This was for the example to work with SimpleServer.js

**Comment by profelec** [comment]
functions 15 and 16 work with events
it's the same way

**Comment by stefanpoeter** [comment]
I do not intend to use every feature from the v2 version. Do you actually use these events or are those just messing with the example (which is still ment to be for v2)?

**Comment by profelec** [comment]
I am switching from version 1 to version 3. 
I am currently using functions 3 and 6 and events.

**Comment by stefanpoeter** [comment]
Well it can't hurt to keep these events in place. Do want to prepare a pull request for those (and the other) events?

**Comment by profelec** [comment]
ok
