### ISSUE TITLE
Callback is called more than once in createTCPClient

### ISSUE THREAD

**Issue by bladerunner2020** [Cloud-Automation/node-modbus#21]
I am not sure if this is an issue at all and I already found a workaround. 

I connect to a number of modbus devices using async.forEach:
`async.forEach(addresses, function(address, iterate_callback){`
`...`
`var client = modbus.createTCPClient(port, host, item, function(err){`
`...`
`return iterate();});`

The callbacks are called reporting on successful connections. Here it's necessary to say couple of words about my configuration - I have a number of modbus devices connected via modbus RS485-to-TCP gateway. If all devices are connected via RS485 to the gateway - everything works fine, but if some devices are not connected to RS485 I got the following issue - the callback for createTCPClient is called second time and I get exception in async module "the callback is already called" (or something).

As I said I already found a workaround - I just use some flags to avoid the calling iterate() callback the second time. Still it was a surprise for me as I didn't expect this callback fired more than once.

-ap

**Comment by BauchBeinePoe** [comment]
The callback is called every time the tcp socket emits an 'connect' event or an 'error' event, so it is possible that the callback gets called more than one time.
