### ISSUE TITLE
Wrong CRC calculation in RTU serial mode

### ISSUE THREAD

**Issue by svobodb** [Cloud-Automation/node-modbus#215]
CRC calculation of serial RTU requests seems to be implemented incorrectly. Client address (first byte) should be included in the calculation (it is skipped currently) and the CRC should be transmitted as little endian (it is transmitted as big endian currently).

I have noticed this because my devices do not respond to the current node-modbus implementation-generated requests.

You can find the fixed rtu-request.js in the attachment: [rtu-request.js.txt](https://github.com/Cloud-Automation/node-modbus/files/2237129/rtu-request.js.txt)

Note that the same problem is in CRC check of the received responses.

**Comment by stefanpoeter** [comment]
Alread fixed in branch v3.1-dev. Will be released soon.
