### ISSUE TITLE
Clarify the license

### ISSUE THREAD

**Issue by dzimine** [Cloud-Automation/node-modbus#218]
While the license text is of MIT, it would be convenient to state it explicitly (inversely it is complicated to include the software when license is anything but crystal clear).

Thank you!

**Comment by cwg999** [comment]
Probably something like 

https://github.com/expressjs/express/blob/master/Readme.md
https://github.com/expressjs/express/blob/master/LICENSE

**Comment by stefanpoeter** [comment]
How about #219
