### ISSUE TITLE
Programmatic exception code response

### ISSUE THREAD

**Issue by kdrews34** [Cloud-Automation/node-modbus#257]
I currently do not see a way to programmatically send an exception code from modbus server on certain requests. For example, Let's say I don't want to support 'read coils' requests, so I want to respond with an 'illegal function' code any time this type of request comes in. If there is a way to do this currently, I would appreciate a simple example use of the functionality.

**Comment by stefanpoeter** [comment]
Hi @kdrews34 what version are you using?

**Comment by flottokarotto** [comment]
I am also looking for that feature, using v3.1.3
