### ISSUE TITLE
Where is API?

### ISSUE THREAD

**Issue by JianJD** [Cloud-Automation/node-modbus#260]
Is there an API document for this？

**Comment by stefanpoeter** [comment]
Hi @JianJD ,

by now there is only the readme. A detailed API documentation is still on my bucket list.

**Comment by JianJD** [comment]
When can you finish this API document？I really need your package now ！！！Thank you

**Comment by stefanpoeter** [comment]
The readme deals with the basics for this library and it should be no problem to go on from there.

However, if you want to participate in this free and open library then you are welcome to commit a more detailed documentation yourself.

**Comment by JianJD** [comment]
Does this package have CRC verification?

**Comment by stefanpoeter** [comment]
Modbus/RTU uses CRC verification and so does this package. Modbus/TCP does not since it is part of TCP.

**Comment by jacobq** [comment]
The server examples don't appear to show how to handle any requests. Am I missing something / not looking in the right place? For example, how can I make a server that responds to a `readCoils` request from the client in the other example?

**EDIT**: found a little more here:https://github.com/Cloud-Automation/node-modbus/blob/master/examples/tcp/SimpleServer.js

It would be nice to update the one in the README or just put a link...would you take a PR for this?

**EDIT 2**: Looks like there are also some mistakes in the examples :(
 For example, in the client `resp.response.body.coils` is `undefined` but `resp.response.body._valuesAsArray` has the expected bits.

**Comment by stefanpoeter** [comment]
Hey @jacobq 

of course I take a PR for this.
