### ISSUE TITLE
MBClient should provide "manuallyRejectAllRequests"

### ISSUE THREAD

**Issue by Suizi11** [Cloud-Automation/node-modbus#268]
I've seen that the abstract class **MBClient** provides following functions:
```
manuallyClearRequests(numRequests: number): void;
manuallyRejectCurrentRequest(): void;
```

However, the class **MBClientRequestHandler** also provides a function `manuallylRejectAllRequests` (guess it's a typo), but the function can't be called since it's not provided by the MBClient (which holds the instance of the request handler). Would be nice if the function is also available in the client which forwards it to the request handler. Or what is the purpose of this method at all?

Thanks.

**Comment by stefanpoeter** [comment]
Hey @Suizi11 

we are always happy for code additions. Seems like a good feature.
