### ISSUE TITLE
Can I use it with Serial-to-Ethernet gateway?

### ISSUE THREAD

**Issue by bladerunner2020** [Cloud-Automation/node-modbus#275]
I have icpdas tds-718 serial-to-ethernet server.
I wonder if I can use node-modus to connect Modbus devices via this gateway without installing virtual com-port?

**Comment by ganadara135** [comment]
Yes  you  can.  If you use the convertor(serial to ethernet), the way of  programming is same like TCP communication.  Check the menual of tds-718

**Comment by bladerunner2020** [comment]
According to the manual, I have to install a virtual com port driver and then work with this port.
