### ISSUE TITLE
read holding registers from SATEC meter

### ISSUE THREAD

**Issue by dyaacov** [Cloud-Automation/node-modbus#292]
I would like to reopen the discussion.
We are using SATEC meter.

The way it works, the meter open connection to the server and then the server request for holding registers.
this way, you don't need to know the meter ip and the meter can be configured with DHCP.

_Originally posted by @dyaacov in https://github.com/Cloud-Automation/node-modbus/issues/281#issuecomment-890575627_

**Comment by stefanpoeter** [comment]
And what do you need to know?
