### ISSUE TITLE
TypeError: Cannot read property 'complete' of undefined

### ISSUE THREAD

**Issue by jrajnhold** [Cloud-Automation/node-modbus#293]
Hi,
I have a problem with a method 'complete'.
For example i try to run Reconnect.js 

_const client = modbus.client.tcp.complete({
  'host': process.argv[2],
  'port': process.argv[3],
  'autoReconnect': false,
  'logEnabled': true
}).connect()_
.......
and I get a ERROR

_const  client = modbus.client.tcp.complete({
                               ^
TypeError: Cannot read property 'complete' of undefined_

Can you fix it?

**Comment by stefanpoeter** [comment]
Hey @jrajnhold, what version do you use?
