### ISSUE TITLE
Handle modbus-tcp messages with too short payload

### ISSUE THREAD

**Issue by arobal** [Cloud-Automation/node-modbus#296]
If a device fails to send a correct (complete) modbus-tcp response, this currently results in a timeout (as message is too short to be handled).
Because the buffer of the ModbusTCPClientResponseHandler will not be resettet/reduced in this case, following valid messages can't be processed any more but fail with further timeout-errors.

![image](https://user-images.githubusercontent.com/72851411/130579495-94dae31b-8d7b-40cb-873c-70f99696897b.png)
![image](https://user-images.githubusercontent.com/72851411/130579601-28954d1c-864c-4481-8f76-972886d00539.png)

This problem can be solved by manually resetting the buffer or do a full reconnect, but is there any better/proposed way to handle this? (dropping the invalid message but beeing able to continue reading)

Thank you

**Comment by arobal** [comment]
Here a screenshot of the (unprofessional workaround) solution for beeing able to further communicate with the Modbus device:
![image](https://user-images.githubusercontent.com/72851411/130581564-59bf65ff-e78b-44f5-b5df-d357615137a0.png)

**Comment by stefanpoeter** [comment]
If the device fails to send a correct message than the software on the device should be fixed. You can of course fork this package and apply your changes and work from here on.
