### ISSUE TITLE
Possible typo in TSDoc

### ISSUE THREAD

**Issue by tukusejssirs** [Cloud-Automation/node-modbus#299]
The following code comes from [`user-request-metrics.ts` (L3-L10)](https://github.com/Cloud-Automation/node-modbus/blob/v4.0-dev/src/user-request-metrics.ts#L3-L10):

```ts
/**
 * Timestamp when the request was sent
 */
public createdAt: Date = new Date()
/**
 * Timestamp when the request was sent
 */
public startedAt: Date = new Date()
```

Both `createdAt` and `startedAt` have the same description, one of them is wrong.

**Comment by stefanpoeter** [comment]
@tukusejssirs Always happy for pull requests :-)
