### ISSUE TITLE
How can I reliably keep a connection alive indefinitely / until I stop it explicitly?

### ISSUE THREAD

**Issue by tukusejssirs** [Cloud-Automation/node-modbus#300]
In my use case, I need to get from Modbus-enabled PLC four Boolean values every second. The number of PLCs can vary; it can be anywhere between 10 and 100. Those PLCs might not be alwayAlso I need to be able to start and stop gathering the data at runtime. I use TypeScript and Nest.js. I use `cron` package to gather the data every second and I am able to stop and stop the cronjob.

Now, I tried to create a function that would be run on `timeout` and `disconnect`, but it does not work as expected (see below). I save a `socket` and a `client` into `this.sockets[machine]` (service-level private variable, where `machine` is used to identify the PLC).

What bugs me the most is when the PLC is not reachable (the machine is turned off): it outputs the error. I want it to ignore the error, sleep for two seconds and try again.

How could I accomplish this? Thanks in advance!

```ts
['timeout', 'disconnect'].forEach((e) => {
  this.sockets[machine].socket.on(e, () => {
    this.connectToModbusServer(machine, host, port)
  })
})

private connectToModbusServer(machine: number, host: string, port = 502): void {
  // I need to stop the cronjob, otherwise it would run the callback every second and thus try to reconnect every second.
  this.cronService.deleteJob(`m${machine}/li`)

  // I made this function sleep for two seconds here, otherwise there would a race condition after first connection was made.
  const timoutId = setTimeout(() => this.logger.debug('>>> waiting for 2 seconds before reconnecting ...'), 2000)
  clearTimeout(timoutId)

  const reconnectInterval = setInterval(() => {
    try {
      this.sockets[machine].socket.connect({host: host, port: port})
    } catch (e) {
      this.logger.debug(e)
      this.logger.debug('>>> should break from catch, waiting for next interval to (re-) connect')
      return
    }

    clearInterval(reconnectInterval)

    // (Re-) create the cronjob
      this.cronService.createJob(`m${machine}/li`, '* * * * * *', () => {
        this.sockets[machine].client
          .readCoils(0, 4)
          .then((resp) => {
            this.logger.debug('[' + resp.metrics.receivedAt.toISOString() + '] : ' + resp.response.body.valuesAsArray.slice(0, 4).toString())
          })
          .catch((err) => {
            this.logger.debug(err)
            this.logger.debug('>>> an error occured while reading coils, trying to reconnect to the server')
            this.connectToModbusServer(machine, host, port)
          })
      })

    this.logger.debug('>>> should be (re-) connected to the server')
  }, 2000)
}
```

**Comment by stefanpoeter** [comment]
Hi @tukusejssirs,

this is a clear applicational problem related to your software and has basically nothing to do with this library. If you encounter any bugs or problems I am happy to help.

Cheers,
Stefan
