### ISSUE TITLE
request fc and response fc does not match.

### ISSUE THREAD

**Issue by anesteziker** [Cloud-Automation/node-modbus#304]
Hello, when I use the single register write method, I get the following error after the first few submissions. I need your help on this.

[Arguments] {
  '0': UserRequestError {
    err: 'OutOfSync',
    message: 'request fc and response fc does not match.',
    response: undefined
  }
}

**Comment by anesteziker** [comment]
[Arguments] {
  '0': UserRequestError {
    err: 'OutOfSync',
    message: 'request fc and response fc does not match.',
    response: undefined
  }
}
[Arguments] {
  '0': UserRequestError {
    err: 'OutOfSync',
    message: 'request fc and response fc does not match.',
    response: undefined
  }
}

**Comment by stefanpoeter** [comment]
Can you provide some code to reproduce this?
