### ISSUE TITLE
RTU server unit ID

### ISSUE THREAD

**Issue by JaagupAverin** [Cloud-Automation/node-modbus#307]
Hello. I am confused as to how, when constructing the RTU server, one can assign the server's unit ID? Right now the server is reacting to all incoming data.
```

**Comment by stefanpoeter** [comment]
Hey @JaagupAverin ,

there isn't any. The serve does not check the unit ID. That is clearly a missing feature but it should not be that hard to implement. Would you care to setup a pull request?

**Comment by KamaxSuen** [comment]
Hi 

I make a simple patch to address this issue. It work for me

[jsmodbus-rtu-unit-id.patch](https://github.com/Cloud-Automation/node-modbus/files/10397821/jsmodbus-rtu-unit-id.patch)

**Comment by stefanpoeter** [comment]
Hi @KamaxSuen 

thanks for your work. Can you put this in a pull request.

**Comment by KamaxSuen** [comment]
> Hi @KamaxSuen
> 
> thanks for your work. Can you put this in a pull request.

Hi @stefanpoeter 

Thanks for appreciation
I'm newcomer in GitHub. I'm not familiar how to create pull request but I will try
