### ISSUE TITLE
Port not open error on TCP connection

### ISSUE THREAD

**Issue by Naim-Bijapure** [Cloud-Automation/node-modbus#312]
hi, I am getting a port not found error on the TCP connection.

actually, we are fetching plc data every 1 minute. the issue is coming after 6-8 hours. I am getting port not found error .
and after node server restart it starts again !

is there any solution for this?
i am on version 8.0.5

 please help

**Comment by stefanpoeter** [comment]
Hi @Naim-Bijapure 

there is no version 8.0.5. Do you have any example code, debug messages or a stack trace?

**Comment by Naim-Bijapure** [comment]
ohh sry i am on wrong repo.  is this
 [node-modbus](https://github.com/Cloud-Automation/node-modbus)

works same as 
[node-modbus-serial](https://github.com/yaacov/node-modbus-serial)

i can try this then
