### ISSUE TITLE
ServerSerial usage?

### ISSUE THREAD

**Issue by MillerRen** [Cloud-Automation/node-modbus#327]
Is this lib can as a serial server? I can see a serial server unit test but can not config it successfully.

**Comment by stefanpoeter** [comment]
Hey,

this should work with a serial device. The initialization is up to the
serialport module. Have a look at their module on how to initialize this.



Am Do., 29. Juni 2023 um 10:22 Uhr schrieb 任羽飞 ***@***.***>:

**Comment by MillerRen** [comment]
Thx. 
I am trying but failed. Will you show me some code example, please?

**Comment by stefanpoeter** [comment]
I am sorry, I don't use the serialport myself. Post something on github as
an issue or look though the closed issues. You may find help there.

Am Do., 29. Juni 2023 um 10:31 Uhr schrieb 任羽飞 ***@***.***>:
