### ISSUE TITLE
Show how to respond with an error code using modbus-server-tcp

### ISSUE THREAD

**Issue by jbockerstette** [Cloud-Automation/node-modbus#34]
Great library. Thank you.

This is not an issue really. I am trying to use your library to respond with illegal address error if the client request a modbus address that does not exist in the database. For example, the client makes a readHoldingRegistersRequest for modbus address 40001. I look up that address and find there is no tags tied to that address. How would I use your modbus server to respond with that error?

Thanks.

**Comment by BauchBeinePoe** [comment]
If you define a buffer with the size 40000 then the server will handle that for you.

See the example in the Readme and try to access holding register outside the buffer range. The server should respond with an error code.
