### ISSUE TITLE
ILLEGAL DATA ADDRESS

### ISSUE THREAD

**Issue by dyaacov** [Cloud-Automation/node-modbus#341]
Hi Guys,

I get an ILLEGAL DATA ADDRESS for a register,
any idea? here is the log:

modbus-client issuing new read holding registers request +0ms
  tcp-client-request-handler registrating new request transaction id 1 unit id 1 length 5 +0ms
  user-request creating new user request with timeout 5000 +0ms
  client-request-handler flushing +0ms
  client-request-handler flushing new request <Buffer 00 01 00 00 00 06 01 03 a0 3c 00 01> +1ms
  client-request-handler request fully flushed, ( error: undefined ) +0ms
  modbus-client received data +173ms
  tcp-response-handler receiving new data <Buffer 00 01 00 00 00 03 01 83 02> +0ms
  tcp-response-handler buffer <Buffer 00 01 00 00 00 03 01 83 02> +0ms
  tcp-response tcp header complete, id 1 protocol 0 length 3 unitId 1 +0ms
  tcp-response buffer <Buffer 00 01 00 00 00 03 01 83 02> +0ms
  response-factory fc 131 payload <Buffer 83 02> +0ms
  tcp-response buffer contains a valid response body +0ms
  tcp-response-handler response id 1 protocol 0 length 3 unit 1 +0ms
  tcp-response-handler reset buffer from 9 to 0 +0ms
  tcp-response not enough data available +1ms
  tcp-response-handler not enough data available to parse +1ms
  client-request-handler incoming response +173ms
  client-request-handler response is a exception +0ms
  client-request-handler flushing +0ms
  client-request-handler no request to be executed +0ms
Failed to readRegisters 2024-05-05T19:32:57.426Z 41020 int16 ILLEGAL DATA ADDRESS

Thanks
D

**Comment by stefanpoeter** [comment]
Hi @dyaacov, can you provide a reproducable piece of code?
