### ISSUE TITLE
Delay on multiple connections error

### ISSUE THREAD

**Issue by lfernando-silva** [Cloud-Automation/node-modbus#36]
I solved that problem with handling more than 1 holding registers separating the connection moment and modbus function moment.

But I have multiple connection failure (ip adresses offline), I think would receive connection refused message for every oflline IP adress, but it doesn't happens. For example, if I have 10 offline IPs, for some connections, I receive 'connection refused', then my system blocking waiting for the connection errors, then it comes as 'connection timeout'. But it take at least 20 seconds, doesnt matter how many IPs are offline (I didnt try with more than 30 IPs).

I think it's not the best way, but I did a tcp probe with the module tcp-ping (https://github.com/apaszke/tcp-ping) and then, if it checks the host is not available, it fired your onSocketError function. It's really faster than wait for the timeout event.

In modbus-client-tcp.js, I changed:

````
var TcpPing = require('tcp-ping')
//on the connect() function
// socket stuffs
            var host = this.host;
            var port = this.port;
            TcpPing.probe(host, port, function (err, available) {
                if (!available) return onSocketError(err);
                socket.connect(port,host);
            }); 
``` 
Is this probe covenient?

**Comment by BauchBeinePoe** [comment]
This is, of course, a convenient way to check your connections.
