### ISSUE TITLE
Stop bits and parity setup

### ISSUE THREAD

**Issue by biancode** [Cloud-Automation/node-modbus#38]
Hi,

is it possible to set the Start bits and parity, please?
May with stampit ?

**Comment by BauchBeinePoe** [comment]
I am on it but the only option I see in the serialport are stopbits.

> dataBits Data Bits, defaults to 8. Must be one of: 8, 7, 6, or 5.
stopBits Stop Bits, defaults to 1. Must be one of: 1 or 2.
parity Parity, defaults to 'none'. Must be one of: 'none', 'even', 'mark', 'odd', 'space'

From the serialport module.

What do you mean with startbit?

**Comment by biancode** [comment]
sorry I mean Stop bits like that config dialog http://bit.ly/2bc3cpb

**Comment by BauchBeinePoe** [comment]
See Pull Request #47 .
