### ISSUE TITLE
WriteMultipleCoils not working

### ISSUE THREAD

**Issue by bsense-rius** [Cloud-Automation/node-modbus#53]
Using the latest release with the supplied test code I found that WriteMultipleCoils examples are not working...

    client.writeMultipleCoils(3, [1, 0, 1, 0, 1, 1]).then(function (resp) {
        console.log(resp); 
    }).fail(console.log);

    client.writeMultipleCoils(3, new Buffer([0x2B]), 6).then(function (resp) {
        console.log(resp); 
    }).fail(console.log);

These are copied from source

Regards

**Comment by BauchBeinePoe** [comment]
Do you have any error messages? What is happenin exactly?

**Comment by BauchBeinePoe** [comment]
Can you confirm that the last version (1.2.3) has fixed this, @bsense-rius ?
