### ISSUE TITLE
Compatibility Issues with new Stampit module

### ISSUE THREAD

**Issue by bsense-rius** [Cloud-Automation/node-modbus#55]
I've tested in linux and windows that if you just fresh install jsmodule it has some compatiblity issues with stampit@3.0.2

So it you run the example from its location, it behaves correctly because within jsmodbus/node_modules dir the older version of stampit@2.1.2 is copied.

However if you just try to run the example outside of the jsmodbus (as it should be) it takes the reference of the project dir/node_modules, where the npm install process puts the latest version of stampit...

It might be a bug... Anyway thanks for your efforts

**Comment by BauchBeinePoe** [comment]
Hi @bsense-rius,

jsmodbus is build with stampit@2.1.2 and not testet with anything above. There are currently no plans to change that.

Greetings,
Stefan

**Comment by bsense-rius** [comment]
Thank you.
