### ISSUE TITLE
Is it possible to get the support of ModbusRTU over TCP

### ISSUE THREAD

**Issue by GermanBluefox** [Cloud-Automation/node-modbus#57]
There are some Modbus RTU <=> TCP gateways in the world.
They just take serial RTU frame and send them via TCP (no MBAP header, but with CRC).
Is it possible to support it?

**Comment by tschombe** [comment]
I would also like to see this feature, a good explanation about it can be found here:
http://www.simplymodbus.ca/TCP.htm

**Comment by GermanBluefox** [comment]
I implemented this feature and can create the PR for this.

https://github.com/ioBroker/ioBroker.modbus/blob/master/lib/modbus-tcp-rtu-client.js

**Comment by BauchBeinePoe** [comment]
Please, do so and I have a look.

**Comment by BauchBeinePoe** [comment]
See Pull Request #81 .

**Comment by theopract** [comment]
Hi Stefan,

I can see you closed the issue but looks like you never merged the pull request. 
Can we expect integration of "Modbus RTU over TCP" functionality in the near future?

**Comment by stefanpoeter** [comment]
It shouldn't be that hard to implement but i myself don't have the need for Modbus RTU over TCP. I am always happy to look into new Feature Requests.

**Comment by theopract** [comment]
Ok, thank you.
