### ISSUE TITLE
Please use `require('serialport')` instead of `require('serialport').SerialPort`

### ISSUE THREAD

**Issue by GermanBluefox** [Cloud-Automation/node-modbus#60]
I tested the serial communication and got:

DEPRECATION: Please use `require('serialport')` instead of `require('serialport').SerialPort`

**Comment by Jotan** [comment]
You have to delete the .SerialPort on the require('Serialport').SerialPort to omit that

**Comment by GermanBluefox** [comment]
I wrote it to BauchBeinePoe, so he can modify this line.

https://github.com/Cloud-Automation/node-modbus/blob/master/src/modbus-serial-client.js#L11
