### ISSUE TITLE
Wrong payload values

### ISSUE THREAD

**Issue by psorowka** [Cloud-Automation/node-modbus#87]
Hi @BauchBeinePoe I unfortunately just realized that I have made some small mistakes in my Put() --> Buffer conversions that where not caught by the existing tests. 

Luckily we have some deep integration tests in our platform and we just stumbled over those :) I am currently going through the code again and started to push fixes to the fix-byte-bugs branch: https://github.com/Cloud-Automation/node-modbus/tree/fix-byte-bugs 

I'll issue the PR when I am done. Just so you know, probably pull the most recent version back from npm for now. sorry!

**Comment by BauchBeinePoe** [comment]
I'll just republish the latest version and reset the version tag. Let me know when you fixed it.
