### ISSUE TITLE
Promise.defer is deprecated

### ISSUE THREAD

**Issue by SystemParadox** [Cloud-Automation/node-modbus#96]
Node 6 prints lots of warnings to the console:

```
(node:7143) Warning: Promise.defer is deprecated and will be removed in a future version. Use new Promise instead.
```

Any chance this could be updated?

Thanks.

**Comment by BauchBeinePoe** [comment]
I'll fix this on the next update (2.0.1). Could be a few days though.

**Comment by psorowka** [comment]
ah.. how did you produce these warnings? I didn't see any of them when switching to that.

Actually I knew it would be deprecated but I figured the chances that @BauchBeinePoe accepts the PR is higher when I don't completely change everything :-D

@BauchBeinePoe I can file a PR for that later today. It is my fault anyway :)

**Comment by BauchBeinePoe** [comment]
@psorowka It's alright. I already fixed it. I'll publish a PR later.

**Comment by BauchBeinePoe** [comment]
@SystemParadox can you check if your warnings are still there with the v2.0.1-Release Pull Request?

**Comment by SystemParadox** [comment]
Warnings are gone. Looks good to me. Thanks :)

**Comment by BauchBeinePoe** [comment]
See #98
